# ================================================
# GerenciamentoProfessores - Testes de Rotas
# Ambiente: Localhost
# Base URL: http://localhost:8000
# ================================================

@host = http://localhost:8000


# CENÁRIOS DE CADASTRO TESTADOS
# 1. Cadastro de um novo professor com sucesso
# 2. Cadastro de um novo professor com CPF inválido
# 3. Cadastro de um novo professor com senha inválido
# 4. Cadastro de um novo professor com email existente
# 5. Cadastro de um novo professor com CPF existente

###
# ------------------------------------------------
# [POST] Criar novo cadastro
# Descrição: Cria um novo usuário no sistema.
# Endpoint: POST /cadastro
# Body: JSON com cpf, nome, email e senha
# Exemplo de resposta esperada: 201 Created
# ------------------------------------------------
POST {{host}}/cadastro
Content-Type: application/json

{
  "cpf": "85214965715",
  "nome": "Victor Sarinho",
  "email": "Sar@uefs.br",
  "senha": "7542"
}

# CENÁRIOS DE LOGIN TESTADOS
# 1. Login com sucesso
# 2. Login com email inválido
# 3. Login com senha inválida

###
# ------------------------------------------------
# [POST] Login de usuário
# Descrição: Realiza login com email e senha.
# Endpoint: POST /login
# Body: JSON com email e senha
# Exemplo de resposta esperada: 200 OK
# ------------------------------------------------
POST {{host}}/login
Content-Type: application/json

{
  "email": "J@uefs.br",
  "senha": "1456"
}
